version: '3'
networks:
  pmfms:
services:
  # Postgres
  postgres:
    image: postgres:12.1
    container_name: postgresql
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: homestead
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: homestead
      SERVICE_TAGS: dev
      SERVICE_NAME: postgresql
    networks:
      - pmfms
  # PHP(Laravel) and Apache
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    networks:
      - pmfms
  # pgAdmin 4
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: 1234
    restart: unless-stopped
    networks:
      - pmfms
